name: diffq
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: diffq/results:latest
          cache-to: type=gha,mode=max,scope=${{github.ref_name}}
          cache-from: type=gha,scope=${{github.ref_name}}
          load: true
          file: Dockerfile-ci
      - run: |
          docker create --name results diffq/results:latest
          docker cp results:/coverage/. coverage/
          docker cp results:/unittest/. unittest/
          docker cp results:/dist/. dist/
        name: Extract Results
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
      - uses: actions/upload-artifact@v3
        with:
          name: unittest
          path: unittest
      - uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist
      - uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: "unittest/**/*.xml"
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: coverage/summary.md
      - name: Write to Job Summary
        run: cat coverage/summary.md >> $GITHUB_STEP_SUMMARY
